apiVersion: v1
kind: Service
metadata:
  name: {{ include "provenance-stack.fullname" . }}-api
  labels:
    {{- include "provenance-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.api.containerPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
