apiVersion: v1
kind: Service
metadata:
  name: {{ include "provenance-stack.fullname" . }}-api
  labels:
    {{- include "provenance-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
